// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL6IT8vssDEdWcQfNBKG4ZoDaej-2TTH8',
    appId: '1:525585669863:web:8f01c6c32212a9b66f8c42',
    messagingSenderId: '525585669863',
    projectId: 'flutter-firebase-dersler-cdb20',
    authDomain: 'flutter-firebase-dersler-cdb20.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-cdb20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBKHlb24-Ob8Tkj8sXCN0Iktg0ebIUO0g',
    appId: '1:525585669863:android:993d4d5cb8d857626f8c42',
    messagingSenderId: '525585669863',
    projectId: 'flutter-firebase-dersler-cdb20',
    storageBucket: 'flutter-firebase-dersler-cdb20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN_iqzAfAQuYFS8a3E9qyc8NzQ5zN8xzw',
    appId: '1:525585669863:ios:99cb8b5a61a585e66f8c42',
    messagingSenderId: '525585669863',
    projectId: 'flutter-firebase-dersler-cdb20',
    storageBucket: 'flutter-firebase-dersler-cdb20.appspot.com',
    androidClientId: '525585669863-krjj56i3vt6hb30e8kgsjo61uhrbald9.apps.googleusercontent.com',
    iosClientId: '525585669863-03dqpp8ngag17nqc27gcpm9ecs4almeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestorePersonsAppProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN_iqzAfAQuYFS8a3E9qyc8NzQ5zN8xzw',
    appId: '1:525585669863:ios:3863d7abd78701256f8c42',
    messagingSenderId: '525585669863',
    projectId: 'flutter-firebase-dersler-cdb20',
    storageBucket: 'flutter-firebase-dersler-cdb20.appspot.com',
    androidClientId: '525585669863-krjj56i3vt6hb30e8kgsjo61uhrbald9.apps.googleusercontent.com',
    iosClientId: '525585669863-ppp0fg2d819rf15iogl2bqcfhsm96oc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestorePersonsAppProvider.RunnerTests',
  );
}
